title:              MPHoward Lab
email:              mph0043@auburn.edu
description:        Computational modeling of materials
author:            
baseurl:            
url:                "https://mayukhkundu14.github.io"

# Social Profiles
twitter_username:   SBootstrap
github_username:    mphoward
linkedin_username:  Michael P. Howard

# Add your google-analytics ID here to activate google analytics
google_analytics:   UA-XXXXXXXXX-X # out your google-analytics code

# Build settings
markdown:           kramdown
paginate:           5
paginate_path:      "/posts/page:num/"
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap ## Uncomment this line to silently generate a sitemaps.org compliant sitemap for your Jekyll site

people:
- name: Mayukh Kundu
  pic: 1
  position: Ph.D Candidate
  social:
    - title: Linkedin
      url: https://www.linkedin.com/in/mayukh-kundu-88679a144?lipi=urn%3Ali%3Apage%3Ad_flagship3_profile_view_base_contact_details%3BySEr3zvnSqmfjCSBTNyTrw%3D%3D
    - title: facebook
      url: #


- name: Chase Levi Petix
  pic: 2
  position: Ph.D. Student
  social:
    - title: twitter
      url: #
    - title: facebook
      url: #
    - title: linkedin
      url: #
